### PR TITLE
FTMS_gatt_server as an example

### PR DESCRIPTION
**Pull request by WouterJD**
FTMSserver creates a bless server with a FTMS profile
FTMSclient inspects what ble-devices are present, searches for FTMS server and prints the service/characteristics structure

FTMSserver is inspired by bless/examples/gattserver.py
FTMSclient is inspired by bleak/examples/discover.py and service_explorer.py

First start FTMSserver, then FTSMclient.

See [QUESTION: How to define the Generic Access Profile (during BlessServer creation)?](https://github.com/kevincar/bless/discussions/76)

### CODE REVIEW

**Comment by kevincar** [comment]
@WouterJD any chance you can get the checks to pass before merge?

**Comment by WouterJD** [comment]
I will give it a try Monday. ThanksMet vriendelijke groetWouter Dubbeldam -------- Oorspronkelijk bericht --------Van: Kevin Davis ***@***.***>Datum: za 28 mei 2022 02:55Aan: kevincar/bless ***@***.***>Cc: Wouter Dubbeldam ***@***.***>, Mention ***@***.***>Onderwerp: Re: [kevincar/bless] FTMS_gatt_server as an example (PR #77)
@WouterJD any chance you can get the checks to pass before merge?

**Comment by WouterJD** [comment]
I must use the development branch to test, right? Met vriendelijke groetWouter Dubbeldam -------- Oorspronkelijk bericht --------Van: Kevin Davis ***@***.***>Datum: za 28 mei 2022 02:55Aan: kevincar/bless ***@***.***>Cc: Wouter Dubbeldam ***@***.***>, Mention ***@***.***>Onderwerp: Re: [kevincar/bless] FTMS_gatt_server as an example (PR #77)
@WouterJD any chance you can get the checks to pass before merge?

**Comment by kevincar** [comment]
Refer to the [contributing guidelines](https://github.com/kevincar/bless/blob/master/CONTRIBUTING.md)

**Comment by WouterJD** [comment]
> @WouterJD any chance you can get the checks to pass before merge?

Yes, BLESS now works fine under windows.
I have tested FTMS_gatt_server as well as FortiusAnt; both recognized well from Trainer Road as a FTMS.

Thanks!

**Comment by kevincar** [comment]
Closing this for now because of CI failures and lots of non generic code for an example.

**Comment by WouterJD** [comment]
> ... non generic code for an example.

Agree; it's a full BLE client/server implementation of a Fitness Machine.

**Pull request closed without merging**
