### PR TITLE
Allow to define descriptor for GATT characteristic

### PR DESCRIPTION
**Pull request by mklemarczyk**
First implementation for Descriptor in linux.
Tested as working feature on Raspberry 4.

Feel free to review and comment.

I noticed that bless library does not expand the uuid from 16 bit and 32 bit form.
I put a proposal to use normalize_uuid_str to expand uuid to full value.

### CODE REVIEW

**Comment by kevincar** [comment]
Thank you for these additions. I sincerely appreciate that you followed the code style so well. I'll merge this to develop but I won't mark this issue as resolved just yet since I'd like to see if windows and macOS could be implemented too. 

Thanks for tackling the DBus backend!

**Comment by foemre** [comment]
Is it possible to provide a simple example for defining descriptors? @mklemarczyk @kevincar

**Comment by mklemarczyk** [comment]
Sure, I will look in it. Sorry, I was off a bit.

**Comment by 12944qwerty** [comment]
I need this for windows or mac. I'm trying to port it for them but I'm not sure what I'm doing. Is there anything to help for it? Any guides to help figure out exactly what I need to do?
There are a lot of extra files and things that just aren't in winrt so I'm extra confused by that too.

**Comment by kevincar** [comment]
@12944qwerty 

A good starting place for mac, check here for the apple documentation on descriptors. 

The `CoreBluetooth` backend will need to convert the generic descriptors into [`CBMutableDescriptor`](https://developer.apple.com/documentation/corebluetooth/cbmutabledescriptor) that can then be added to the characteristics.

Good to dive into the code. Especially how Bless generalizes the classes. Check out the files in the [backend](https://github.com/kevincar/bless/tree/develop/bless/backends) folders. Then, look at how those related to the specific implementation, such as [CoreBluetooth](https://github.com/kevincar/bless/tree/develop/bless/backends/corebluetooth). Notice how there is a generic `service.py` for a specific `service.py`. @mklemarczyk already went ahead and created the generic `descriptor.py` for Bless and the `descriptor.py` for BlueZ. There needs to be an implementation for `CoreBluetooth` and for `winrt` for Windows.

**Pull request merged**
